name: Ruff format
permissions:
  contents: read
on:
  release:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3.5.1
        with:
          args: "format --check --diff"
